# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/logViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logViewer(object):
    def setupUi(self, logViewer):
        logViewer.setObjectName("logViewer")
        logViewer.resize(640, 587)
        logViewer.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        logViewer.setFont(font)
        logViewer.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(logViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.button_saveAs = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_saveAs.sizePolicy().hasHeightForWidth())
        self.button_saveAs.setSizePolicy(sizePolicy)
        self.button_saveAs.setObjectName("button_saveAs")
        self.gridLayout.addWidget(self.button_saveAs, 5, 0, 1, 1)
        self.button_Save = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Save.sizePolicy().hasHeightForWidth())
        self.button_Save.setSizePolicy(sizePolicy)
        self.button_Save.setObjectName("button_Save")
        self.gridLayout.addWidget(self.button_Save, 5, 1, 1, 1)
        self.logFileWindow = QtWidgets.QTextEdit(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logFileWindow.sizePolicy().hasHeightForWidth())
        self.logFileWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.logFileWindow.setFont(font)
        self.logFileWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logFileWindow.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logFileWindow.setObjectName("logFileWindow")
        self.gridLayout.addWidget(self.logFileWindow, 4, 0, 1, 6)
        self.button_deleteLog = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_deleteLog.sizePolicy().hasHeightForWidth())
        self.button_deleteLog.setSizePolicy(sizePolicy)
        self.button_deleteLog.setObjectName("button_deleteLog")
        self.gridLayout.addWidget(self.button_deleteLog, 5, 4, 1, 1)
        self.button_quit = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_quit.sizePolicy().hasHeightForWidth())
        self.button_quit.setSizePolicy(sizePolicy)
        self.button_quit.setObjectName("button_quit")
        self.gridLayout.addWidget(self.button_quit, 5, 5, 1, 1)
        self.label_Path = QtWidgets.QLabel(logViewer)
        self.label_Path.setObjectName("label_Path")
        self.gridLayout.addWidget(self.label_Path, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(logViewer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_fileName = QtWidgets.QLabel(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fileName.sizePolicy().hasHeightForWidth())
        self.label_fileName.setSizePolicy(sizePolicy)
        self.label_fileName.setObjectName("label_fileName")
        self.gridLayout.addWidget(self.label_fileName, 0, 1, 1, 5)
        self.label_lastUpdated = QtWidgets.QLabel(logViewer)
        self.label_lastUpdated.setObjectName("label_lastUpdated")
        self.gridLayout.addWidget(self.label_lastUpdated, 1, 1, 1, 4)
        self.label_debugText = QtWidgets.QLabel(logViewer)
        self.label_debugText.setObjectName("label_debugText")
        self.gridLayout.addWidget(self.label_debugText, 5, 2, 1, 2)

        self.retranslateUi(logViewer)
        QtCore.QMetaObject.connectSlotsByName(logViewer)

    def retranslateUi(self, logViewer):
        _translate = QtCore.QCoreApplication.translate
        logViewer.setWindowTitle(_translate("logViewer", "Log Viewer"))
        self.button_saveAs.setText(_translate("logViewer", "Save As"))
        self.button_Save.setText(_translate("logViewer", "Save"))
        self.logFileWindow.setHtml(_translate("logViewer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\',\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\',\'Courier\';\"><br /></p></body></html>"))
        self.logFileWindow.setPlaceholderText(_translate("logViewer", "SampleText1 SampleText2"))
        self.button_deleteLog.setText(_translate("logViewer", "Delete Log"))
        self.button_quit.setText(_translate("logViewer", "Exit"))
        self.label_Path.setText(_translate("logViewer", "Log Path:"))
        self.label_2.setText(_translate("logViewer", "Last Update:"))
        self.label_fileName.setText(_translate("logViewer", "*log Name"))
        self.label_lastUpdated.setText(_translate("logViewer", "*last updated*"))
        self.label_debugText.setText(_translate("logViewer", "*debug text*"))
