# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/Documents/GitHub/SerialKiller//ui_files/serial_killer_help_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help_popup(object):
    def setupUi(self, help_popup):
        help_popup.setObjectName("help_popup")
        help_popup.resize(640, 587)
        help_popup.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        help_popup.setFont(font)
        help_popup.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(help_popup)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_file = QtWidgets.QTextEdit(help_popup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_file.sizePolicy().hasHeightForWidth())
        self.textEdit_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.textEdit_file.setFont(font)
        self.textEdit_file.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_file.setObjectName("textEdit_file")
        self.gridLayout.addWidget(self.textEdit_file, 1, 0, 1, 2)

        self.retranslateUi(help_popup)
        QtCore.QMetaObject.connectSlotsByName(help_popup)

    def retranslateUi(self, help_popup):
        _translate = QtCore.QCoreApplication.translate
        help_popup.setWindowTitle(_translate("help_popup", "Help"))
