# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/Documents/GitHub/SerialKiller//ui_files/serial_killer_log_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logViewer(object):
    def setupUi(self, logViewer):
        logViewer.setObjectName("logViewer")
        logViewer.resize(640, 587)
        logViewer.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        logViewer.setFont(font)
        logViewer.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(logViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Path = QtWidgets.QLabel(logViewer)
        self.label_Path.setObjectName("label_Path")
        self.gridLayout.addWidget(self.label_Path, 0, 0, 1, 1)
        self.label_debugText = QtWidgets.QLabel(logViewer)
        self.label_debugText.setObjectName("label_debugText")
        self.gridLayout.addWidget(self.label_debugText, 4, 2, 1, 2)
        self.textEdit_file = QtWidgets.QPlainTextEdit(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_file.sizePolicy().hasHeightForWidth())
        self.textEdit_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.textEdit_file.setFont(font)
        self.textEdit_file.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_file.setPlainText("")
        self.textEdit_file.setObjectName("textEdit_file")
        self.gridLayout.addWidget(self.textEdit_file, 3, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(logViewer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.button_deleteLog = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_deleteLog.sizePolicy().hasHeightForWidth())
        self.button_deleteLog.setSizePolicy(sizePolicy)
        self.button_deleteLog.setObjectName("button_deleteLog")
        self.gridLayout.addWidget(self.button_deleteLog, 4, 5, 1, 1)
        self.pushButton_save_as = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_as.sizePolicy().hasHeightForWidth())
        self.pushButton_save_as.setSizePolicy(sizePolicy)
        self.pushButton_save_as.setObjectName("pushButton_save_as")
        self.gridLayout.addWidget(self.pushButton_save_as, 4, 0, 1, 1)
        self.label_last_updated = QtWidgets.QLabel(logViewer)
        self.label_last_updated.setObjectName("label_last_updated")
        self.gridLayout.addWidget(self.label_last_updated, 1, 1, 1, 4)
        self.button_Save = QtWidgets.QPushButton(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Save.sizePolicy().hasHeightForWidth())
        self.button_Save.setSizePolicy(sizePolicy)
        self.button_Save.setObjectName("button_Save")
        self.gridLayout.addWidget(self.button_Save, 4, 1, 1, 1)
        self.label_log_name = QtWidgets.QLabel(logViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_log_name.sizePolicy().hasHeightForWidth())
        self.label_log_name.setSizePolicy(sizePolicy)
        self.label_log_name.setObjectName("label_log_name")
        self.gridLayout.addWidget(self.label_log_name, 0, 1, 1, 5)

        self.retranslateUi(logViewer)
        QtCore.QMetaObject.connectSlotsByName(logViewer)

    def retranslateUi(self, logViewer):
        _translate = QtCore.QCoreApplication.translate
        logViewer.setWindowTitle(_translate("logViewer", "Log Viewer"))
        self.label_Path.setText(_translate("logViewer", "Log Path:"))
        self.label_debugText.setText(_translate("logViewer", "*debug text*"))
        self.label_2.setText(_translate("logViewer", "Last Update:"))
        self.button_deleteLog.setText(_translate("logViewer", "Delete Log"))
        self.pushButton_save_as.setText(_translate("logViewer", "Save As"))
        self.label_last_updated.setText(_translate("logViewer", "*last updated*"))
        self.button_Save.setText(_translate("logViewer", "Save"))
        self.label_log_name.setText(_translate("logViewer", "*log Name*"))
